#!/bin/sh
# Copyright (C) 2000-2017 Synology Inc. All rights reserved.

case $1 in
	start)
		/sbin/insmod $SYNOPKG_PKGDEST/hello_kernel/hello_kernel.ko
		exit 0
	;;
	stop)
		/sbin/rmmod $SYNOPKG_PKGDEST/hello_kernel/hello_kernel.ko
		exit 0
	;;
	status)
		/sbin/lsmod | grep hello_kernel && exit 0 || exit 3
	;;
	killall)
        ;;
	log)
		exit 0
	;;
esac

